import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import UserMenu from "@/components/user-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar
          menuItems={[
            { name: "Home", href: "/" },
            { name: "Products", href: "/products" },
            { name: "Sobre Nosotros", href: "/about-us" },
          ]}
          userMenu={
            <UserMenu
              imageSrc="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
              menuItems={[
                { label: "Your Profile", href: "/profile" },
                { label: "Settings", href: "/settings" },
                { label: "Sign out", href: "/signout" },
              ]}
            />
          }
        />
        {children}
      </body>
    </html>
  );
}
